## Practice

In [1]:
import numpy as np
import pandas as pd

In [13]:
a=np.array([[1,2,3],[3,4,5],[7,8,9]])
print(a.shape)
print(a.size)
print(a.ndim)
print(a.reshape(3,1,3))

(3, 3)
9
2
[[[1 2 3]]

 [[3 4 5]]

 [[7 8 9]]]


In [18]:
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]).reshape(3,3,2)
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [27]:
d=np.ones((4,3,4),dtype=int)
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [28]:
e=np.zeros((4,3,4),dtype=int)
e

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [29]:
np.empty([2,2],dtype=int)

array([[7274574, 6619254],
       [6422637, 7471205]])

In [34]:
f=np.array([[1,4],[7,8]])
print(f)
print(np.zeros_like(f))
print(np.empty_like(f))
print(np.ones_like(f))

[[1 4]
 [7 8]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]


In [47]:
g=np.full((2,5,5),21)
print(g)

[[[21 21 21 21 21]
  [21 21 21 21 21]
  [21 21 21 21 21]
  [21 21 21 21 21]
  [21 21 21 21 21]]

 [[21 21 21 21 21]
  [21 21 21 21 21]
  [21 21 21 21 21]
  [21 21 21 21 21]
  [21 21 21 21 21]]]


In [54]:
h=np.arange(100)
h=h.reshape(4,5,5)
print(np.full_like(h,143))

[[[143 143 143 143 143]
  [143 143 143 143 143]
  [143 143 143 143 143]
  [143 143 143 143 143]
  [143 143 143 143 143]]

 [[143 143 143 143 143]
  [143 143 143 143 143]
  [143 143 143 143 143]
  [143 143 143 143 143]
  [143 143 143 143 143]]

 [[143 143 143 143 143]
  [143 143 143 143 143]
  [143 143 143 143 143]
  [143 143 143 143 143]
  [143 143 143 143 143]]

 [[143 143 143 143 143]
  [143 143 143 143 143]
  [143 143 143 143 143]
  [143 143 143 143 143]
  [143 143 143 143 143]]]


In [55]:
a=[10,20,30,40,50]
a

[10, 20, 30, 40, 50]

In [59]:
a=pd.Series(a,index=[1,2,3,4],dtype=int)
a

1    20
2    30
3    40
4    50
dtype: int32

In [60]:
df=pd.DataFrame({"data":[10,20,30,40,50,60,70,80,90,100],"Year":[1,2,3,4,5,6,7,8,9,10]})
df


data  Year
0    10     1
1    20     2
2    30     3
3    40     4
4    50     5
5    60     6
6    70     7
7    80     8
8    90     9
9   100    10

In [62]:
h=df.rename(columns={'data':'data1','Year':'Year1'})
h

data1  Year1
0     10      1
1     20      2
2     30      3
3     40      4
4     50      5
5     60      6
6     70      7
7     80      8
8     90      9
9    100     10

In [63]:
i=df.head()
i

data  Year
0    10     1
1    20     2
2    30     3
3    40     4
4    50     5

In [64]:
j=df.tail()
j

data  Year
5    60     6
6    70     7
7    80     8
8    90     9
9   100    10

In [66]:
k=pd.concat([i,j])
k

data  Year
0    10     1
1    20     2
2    30     3
3    40     4
4    50     5
5    60     6
6    70     7
7    80     8
8    90     9
9   100    10

In [67]:
a= pd.DataFrame({'price':[1,3,5,7],'item':['sticker','mirror','glass','abc'],
                 'manufacture':[2011,2001,2012,2019]},index=['a','b','c','d'])
a

price     item  manufacture
a      1  sticker         2011
b      3   mirror         2001
c      5    glass         2012
d      7      abc         2019