# DATA ANALYSIS

## Data: Information

### Types of Data:
-  1.Structure Data:
   - Examples are student information,database files,csv data,excell data etc....
- 2.Unstructure Data:
   - Examples are images,videos,emails etc....

## Python Libraries:
 - Toolboxes/Libraries:
   - NUMPY
   - SCI PY
   - Pandas
   - Scikit Learn
 -  Visualisation Libraries:
    - Matplotlib
    - seaborn

## NUMPY

  - NumPy is a general-purpose array-processing package. It provides a high-performance               multidimensional array object,and tools for working with these arrays. 
    It is thefundamental package for scientific computing with Python.
    
  - It is Foundational package for numerical computing in python.
  
  - NumPy uses much less memory to store data.
  
  - A numpy array is a grid of values, all of the same type, and is indexed by a tuple 
    of nonnegative integers...Numpy data structures perform better in
     Size - Numpy data structures take up less space.

## Multidimensional Array
 - oneof the key features of NUMPY is its N-dimensional array object,or ndarray,which is            fast,flexible container for large database in python.Array enable you to perform                  mathematical operations on whole blocks of data with similar syntax to scalar values on          built-in python objects.

In [73]:
import numpy as np

In [74]:
a = np.array([1,2,3,4,5])
print(a.size)
print(a.ndim)

5
1


In [75]:
b = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(b.shape)
print(b.size)
print(b.ndim)

(3, 3)
9
2


In [76]:
c =np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c.ndim)
print(c.shape)# 1 is sets,3 is rows,3 is columns
print(c.size)
print(c.reshape(3,1,3))

3
(1, 3, 3)
9
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [77]:
d=np.array([[1,2,3],[4,5,6]])
d.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
f= np.array([[1,2,3],[4,5,'6']],dtype='float32')
f

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [95]:
e=np.array([1,2,3,4,5,6,7,8,9],dtype=float,ndmin=3).reshape(3,1,3)
print(e)

[[[1. 2. 3.]]

 [[4. 5. 6.]]

 [[7. 8. 9.]]]
