## MATRIX
 - Matrix Multipliclation
   - multiplication of two matrix
   - dot functionality uses
 - Matrix Addition
   - Addition of two matrix with same shape
 - Matrix Transpose
   - Changes rows to columns and columns to rows
 - Ravel
   - Ravel return reference/view of original array where as
   - If you modify the array you would notice that the value of original array also changes by using.
 - Flatten
   - Flatten returns copy of original array
   - If you moidify the array you would  notice that the value of original array not changes.
 - Argmin
   - Argmin function return index position of the minimum value in array based on axis(0,1)
 - Argmax
   - Argmax function return index position of the maximum value in array based on axis(0,1)
 - Vstack
   - Vstack function return vertical array 
 - Hstack
   - Hstack function return horizontal array 
   

In [1]:
import numpy as np

In [23]:
a= np.array([[1,7,6],[5,6,8]])
a

array([[1, 7, 6],
       [5, 6, 8]])

In [24]:
b= np.array([[3,8,9],[67,89,8]])
b

array([[ 3,  8,  9],
       [67, 89,  8]])

In [25]:
a.dot(b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [21]:
e=np.array([1,2,3,6,7,8,29,19,34,50])
e[-2]=67
e

array([ 1,  2,  3,  6,  7,  8, 29, 19, 67, 50])

In [26]:
a+b

array([[ 4, 15, 15],
       [72, 95, 16]])

In [39]:
b.transpose(3,2,2)

ValueError: axes don't match array

In [48]:
arr1=np.array([[1,2,3,4],[4,5,6,7]])
arr2=np.array([[7,6,8,6],[7,2,4,5]])
c=np.concatenate([arr1,arr2],axis=0)
c

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 6, 8, 6],
       [7, 2, 4, 5]])

In [69]:
f=np.array([[1,2,3],[4,5,6],[7,8,9]])
g=np.ravel(f)
print(f,g)
g[-1]=10
print(f)
print(g)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [1 2 3 4 5 6 7 8 9]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[ 1  2  3  4  5  6  7  8 10]


In [70]:
f[2][0]=12
f,g

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [12,  8, 10]]), array([ 1,  2,  3,  4,  5,  6, 12,  8, 10]))

In [78]:
p=np.array([[1,2,3],[9,8,7]])
print('array:',p)
d=p.flatten()
d[3]=10
d,p

array: [[1 2 3]
 [9 8 7]]


(array([ 1,  2,  3, 10,  8,  7]), array([[1, 2, 3],
        [9, 8, 7]]))

In [81]:
k=np.array([12,34545,6745674,5687678,34523,647567])
print(k.argmax())
k.argmin()

2


0

In [98]:
l=np.array([[4,5,6],[5674,3456,678],[3456,34,645787]])
print(l)
print('Row wise:',l.argmax(axis=1))
print('coloumn wise:',l.argmax(axis=0))

[[     4      5      6]
 [  5674   3456    678]
 [  3456     34 645787]]
Row wise: [2 0 2]
coloumn wise: [1 1 2]


In [104]:
l=np.array([[34,55,66],[4,34,678],[3456,34,6]])
print(l)
print('Row wise:',l.argmin(axis=1))
print('coloumn wise:',l.argmin(axis=0))

[[  34   55   66]
 [   4   34  678]
 [3456   34    6]]
Row wise: [0 0 2]
coloumn wise: [1 1 2]


In [111]:
s=np.array([[2,4,6],[6,8,10]])
t=np.array([[1,3,5],[5,7,9]])
print('s-array:',s)
print('t-array:',t)
print('vertical:',np.vstack((s,t)))
print('Horizontal',np.hstack((s,t)))

s-array: [[ 2  4  6]
 [ 6  8 10]]
t-array: [[1 3 5]
 [5 7 9]]
vertical: [[ 2  4  6]
 [ 6  8 10]
 [ 1  3  5]
 [ 5  7  9]]
Horizontal [[ 2  4  6  1  3  5]
 [ 6  8 10  5  7  9]]
