## Practice on Numpy and Pandas

In [1]:
import numpy as np
import pandas as pd

1. Write a Pandas program to change the order of index of a given series.

In [24]:
a=[10,20,30,40,50]
a=pd.Series(a)
a.index


RangeIndex(start=0, stop=5, step=1)

7.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [10]:
b=np.arange(start=1,stop=10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

8.Illustrate the difference between ravel and flatten by taking considering multidimensional array.

In [22]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
d=c.flatten()
e=c.ravel()
c[-1]=23
print('flatten array:',d)
print('ravel array:',e)

flatten array: [1 2 3 4 5 6 7 8 9]
ravel array: [ 1  2  3  4  5  6 23 23 23]


2. Write a Python program to add, subtract, multiple and divide two Pandas
Series.
        Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [33]:
f=[2,4,6,8,10]
g=[1,3,5,7,9]
f=pd.Series(f)
g=pd.Series(g)
print('Addition:',f+g)
print('Subtract:',abs(f-g))
print('Multiplication:',f*g)
print('Division:',(f/g))

Addition: 0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract: 0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiplication: 0     2
1    12
2    30
3    56
4    90
dtype: int64
Division: 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


10. Illustrate the concept of splitting by taking random positive values and also
implementing different stacking methods on them.

In [54]:
h=np.arange(10)
i=np.arange(start=10,stop=20)
print("v-stack:\n",np.vstack((h,i)))
print("h-stack:\n",np.hstack((h,i)))


v-stack:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
h-stack:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


9. Create a 3×3 numpy array, find out the Minimum,Maximum values and also their
indices accordingly for each axes. Also find out the Statistical methods such as
Standard Deviation,Cumulative sum and product.

In [58]:
j=np.array([[1,3,5],[2,4,6],[7,8,9]])
print(j.cumsum())
print(j.cumprod())
print(j.std())

[ 1  4  9 11 15 21 28 36 45]
[     1      3     15     30    120    720   5040  40320 362880]
2.581988897471611
